//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyyTravel.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Econome
    {
        public int ID_Eco { get; set; }
        public Nullable<long> SeatsEconome { get; set; }
        public Nullable<int> IDPlane { get; set; }
    
        public virtual Plane Plane { get; set; }
        public virtual Plane Plane1 { get; set; }
    }
}
