//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyyTravel.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int ID_flight { get; set; }
        public string Cost { get; set; }
        public Nullable<int> ID_Plane { get; set; }
        public Nullable<int> To_Country { get; set; }
        public Nullable<int> From_Country { get; set; }
        public Nullable<int> To_City { get; set; }
        public Nullable<int> From_City { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> FlightTime { get; set; }
        public Nullable<int> Transfer_status { get; set; }
        public Nullable<int> Path_status { get; set; }
        public string Travel_time { get; set; }
        public Nullable<int> Transfer_Company { get; set; }
        public Nullable<System.DateTime> From_Day { get; set; }
        public Nullable<System.DateTime> To_Day { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual Contries Contries { get; set; }
        public virtual Contries Contries1 { get; set; }
        public virtual Path Path { get; set; }
        public virtual Plane Plane { get; set; }
        public virtual Transfer Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
