//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyyTravel.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.UserInf1 = new HashSet<UserInf>();
        }
    
        public int ID_Ticket { get; set; }
        public Nullable<int> ID_passenger { get; set; }
        public Nullable<int> IdPlane { get; set; }
        public Nullable<int> FromCity { get; set; }
        public Nullable<int> ToCity { get; set; }
        public Nullable<int> From_AirPort { get; set; }
        public Nullable<int> To_AirPort { get; set; }
        public Nullable<int> Class_Ticket { get; set; }
        public Nullable<int> ID_Flight { get; set; }
        public string Seat { get; set; }
        public Nullable<int> Boarding_gate { get; set; }
        public Nullable<int> NameTerminal { get; set; }
        public Nullable<int> QRCode { get; set; }
    
        public virtual Aeroports Aeroports { get; set; }
        public virtual Aeroports Aeroports1 { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual ClassID ClassID { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Gate Gate { get; set; }
        public virtual Plane Plane { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual UserInf UserInf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInf> UserInf1 { get; set; }
    }
}
